{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prodcons.serviceAccountName" . }}
  labels:
{{ include "prodcons.labels" . | nindent 4 }}
{{- end -}}
